### ISSUE TITLE
Allow line numbered output

### ISSUE THREAD

**Issue by jidanni** [kwattsorg/adbshellkit#10]
Perhaps add an option to number the lines of the output. We can't just pipe the output to "nl -b a" ourselves.

**Comment by kwatkins** [comment]
Hmm... I like the pipe to nl solution (wasn't aware of nl, thanks for that!), numbering in the UI is a bit messy... let's get pipes working!

**Comment by kwatkins** [comment]
with pipes nl -b -a works fine
