### ISSUE TITLE
Don't go back to the first command so often

### ISSUE THREAD

**Issue by jidanni** [kwattsorg/adbshellkit#14]
It seems all too often we end up back at the top of the list, at system/bin/id.
 it would be better to try and remember where we were at all times. No, currently I can't exactly reproduce what makes it go back to the first one, but it often does.

**Comment by kwatkins** [comment]
Yeah this is tricky, since any updates (public or private) to the cloud refresh the UI.  

Ideally even if you close the app, it should, on the next run, start where it was last. 

This can be done.

**Comment by kwatkins** [comment]
I've added timestamps and ordering of commands by last run 
Also, cleaned up the view adapter to hold commands and ordering, it was stupid to keep and try and track that outside of it.
