### ISSUE TITLE
Include, check, and request Android runtime permissions when executing commands

### ISSUE THREAD

**Issue by kwatkins** [kwattsorg/adbshellkit#5]
Create a field for commands that lists permissions used and required at runtime for commands. When the user selects and runs the command, check for those permissions are already granted, if not popup the runtime permission request with details including the command and why it requires those permissions.

**Comment by gabasch85** [comment]
https://github.com/kwattsorg/adbshellkit.wiki.git

**Comment by kwatkins** [comment]
this has been added!
