### ISSUE TITLE
 don't show path on contributed commands

### ISSUE THREAD

**Issue by jidanni** [kwattsorg/adbshellkit#7]
In the big list of contributed commands that we see when we open the app, can you please remove the full path from most of them?
We checked the option to use the path, so we don't need the distraction of seeing that path shown on most of the commands.

**Comment by kwatkins** [comment]
Hmm good call, path isn't even needed to make the command run. Will do this.

**Comment by alialooooosh055455** [comment]
**_ 😄 _ **

**Comment by kwatkins** [comment]
Done for the most part, might be a few public commands still with paths and will rename when encountered
