### ISSUE TITLE
 Enable pipes

### ISSUE THREAD

**Issue by jidanni** [kwattsorg/adbshellkit#8]
Please allow us to use pipes. There is no reason why "ls ¦ wc" cannot be made to work.

**Comment by kwatkins** [comment]
Fully agreed. Let's get this one working, and tbh, I thought they did work, something with the shell library I'm using might be breaking this - this is a bug.

**Comment by kwatkins** [comment]
@jidanni let me know if pipes still don't work, they should!

**Comment by jidanni** [comment]
Well, version 7.0 is still on Google Play, so I don't know if the problem is fixed yet.

**Comment by jidanni** [comment]
```
sh: <stdin>[9]: /system/bin/id¦wc: not found
```
 version 8.0
